<?php

require_once 'C:\wamp\www\framework\db.php';
require_once 'C:\wamp\www\framework\databaseAdapter.php';

/**
 * Test class for table.
 * Generated by PHPUnit on 2011-03-20 at 19:22:16.
 */
class tableTest extends PHPUnit_Framework_TestCase {

    /**
     * @var table
     */
    protected $dbCon;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
		
    }

	public function tableProvider() {
		$this->dbCon  = new MySQLiDatabase('localhost','root','','test');

		return array(
			array(new table('maintabel',FALSE,FALSE,$this->dbCon),'many2main','id','id_maintabel')
			);
	}
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFind().
     */
    public function testFind() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

	public function connectProv() {
		return array(
			array('many2main','id','id_maintabel')
			);
	}
    /**
		@dataProvider tableProvider
     */
    public function testAddRelation($table,$connectTable,$id,$connid) {
		$table->addRelation($connectTable,$id,$connid);
    }

    /**
     * @todo Implement testAddRelationM2M().
     */
    public function testAddRelationM2M() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetAll().
     */
    public function testSetAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testImportRows().
     */
    public function testImportRows() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }


}

?>
